# Generated by Django 4.2.5 on 2023-10-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genetic_algorithm", "0005_delete_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptimizationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("best_solution", models.JSONField()),
                ("fitness", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
